site_name: 内容管理平台
site_url: https://www.nbook.online
site_description: Project documentation with Markdown.
site_author: Anson Cheung
 
docs_dir: docs

theme: spacelab

nav:
    - 概述: index.md
    - 内容管理平台:
        -  部署手册: ecmp_server_deploy_product.md
        -  操作手册: ecmp_server_operation_product.md
        -  运维手册: ecmp_server_maintenance_product.md
    - 缓存服务器:
        -  部署手册: ecmp_cache_deploy_product.md
        -  操作手册: ecmp_cache_operation_product.md
        -  运维手册: ecmp_cache_maintenance_product.md
    - 第三方产品运维:
        - GTP运维手册: tongtech_gtp_maintenance_product.md 
        - Documentum运维手册:  emc_documentum_maintenance_product.md  
    - 常见问题:
        - 常见故障排除: troubleshooting.md 
        - 自助故障排除: auxiliary_troubleshooting.md 
        - 服务器环境信息: environment_list.md
    - 关于:
        - 版本信息: release_notes.md
        - 技术支持: technical_support.md
copyright: 中国人民银行  &#8226;  金电技术开发中心
 
plugins: 
    - search
    - with-pdf
