site_name: Gradle 使用参考
site_url: https://www.nbook.online
site_description: Project documentation with Markdown.
site_author: Anson Cheung
 
docs_dir: docs
theme: ivory
# theme: mkdocs
# theme: readthedocs
 
 
copyright: 中国人民银行  &#8226;  金电技术开发中心 
 
plugins: 
#    - search
    - with-pdf:
        author: 张晓华
        #copyright: 金电技术开发中心
        #
        #cover: true
        #cover_title: 内容管理平台
        #cover_subtitle: 运维手册
        #heading_shift: true
        #toc_level: 3
        #ordered_chapter_level: 2
        #excludes_children:
        #    - 'release-notes/:upgrading'
        #    - 'release-notes/:changelog'
        #
        #output_path: ecmp-document.pdf
        #enabled_if_env: ENABLE_PDF_EXPORT
        #
        #debug_html: true
        #verbose: true
