site_name: CompTIA Linux+
site_url: https://www.nbook.online
site_description: Project documentation with Markdown.
site_author: Anson Cheung
 
docs_dir: docs
theme: ivory
dev_addr: 127.0.0.1:8080

  
copyright: 中国人民银行  &#8226;  金电技术开发中心
 
markdown_extensions:
    - smarty
    - toc:
        permalink: false
        baselevel: 2
    - sane_lists
plugins:
    - search
    - with-pdf
